# Setup
title:               Vamsi
tagline:             'Music | Coffee | Code | Swim | Sleep'
description:         'I am a senior software developer working on backend development'
url:                 http://127.0.0.1:4000
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Vamsi Krishna Kolluri
  url:               https://twitter.com/mdo
  email:             kolvakri@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15