# Setup
title:               Vamsi
tagline:             'Music|Code|Coffee'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://www.vkolluri.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Vamsi Krishna Kolluri
  url:               https://twitter.com/mdo
  email:             kolvakri@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
